name: "Setup Minecraft"
author: "mcenv"
description: "Setup a Minecraft server"
inputs:
  version:
    description: "Minecraft version to use"
    required: false
    default: "release"
  install:
    description: "Whether to install Minecraft"
    required: false
    default: true
outputs:
  version:
    description: "Minecraft version used"
  package:
    description: "Package used"
runs:
  using: "node16"
  main: "index.js"
branding:
  icon: "box"
  color: "gray-dark"
