export const VERSION_MANIFEST_V2_URL = "https://launchermeta.mojang.com/mc/game/version_manifest_v2.json";
export const MINECRAFT = "minecraft";

export const INPUT_VERSION = "version";
export const INPUT_EULA = "eula";

export const INPUT_PROPERTIES = [
    "online-mode",
    "prevent-proxy-connections",
    "server-ip",
    "spawn-animals",
    "spawn-npcs",
    "pvp",
    "allow-flight",
    "resource-pack",
    "require-resource-pack",
    "resource-pack-prompt",
    "motd",
    "force-gamemode",
    "enforce-whitelist",
    "difficulty",
    "gamemode",
    "level-name",
    "server-port",
    "enable-query",
    "query.port",
    "enable-rcon",
    "rcon.port",
    "rcon.password",
    "resource-pack-sha1",
    "hardcore",
    "allow-nether",
    "spawn-monsters",
    "snooper-enabled",
    "use-native-transport",
    "enable-command-block",
    "spawn-protection",
    "op-permission-level",
    "function-permission-level",
    "max-tick-time",
    "rate-limit",
    "view-distance",
    "max-players",
    "network-compression-threshold",
    "broadcast-rcon-to-ops",
    "broadcast-console-to-ops",
    "max-world-size",
    "sync-chunk-writes",
    "enable-jmx-monitoring",
    "enable-status",
    "entity-broadcast-range-percentage",
    "text-filtering-config",
    "player-idle-timeout",
    "white-list",
    "generator-settings",
    "level-seed",
    "generate-structures",
    "level-type"
];

export const OUTPUT_VERSION = "version";
